// Import necessary packages
const https = require("https"); // Import the HTTPS module
const fs = require("fs"); // Import the File System module
const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
require("dotenv").config(); // Load environment variables from .env file
//Creating an express app
const app = express();

// Configure middleware functions
app.use(express.json({ limit: "100mb" }));
app.use(express.urlencoded({ limit: "100mb", extended: true }));
app.use(cors());

const PORT = process.env.PORT; // Get port number from environment variables
const URI = process.env.URI; // Get MongoDB URI from environment variables
// Reading SSL certificate and private key generated by mkcert
const options = {
  key: fs.readFileSync("../certificate/localhost-key.pem"), // Path to the private key file
  cert: fs.readFileSync("../certificate/localhost.pem"), // Path to the certificate file
};

// Connecting to the MongoDB database and starting the HTTPS server
mongoose
  .connect(URI, { useUnifiedTopology: true })
  .then(() => {
    console.log("Connection to MongoDB successful");

    // Creating HTTPS server with SSL certificate
    https.createServer(options, app).listen(PORT, () => {
      console.log(`Secure server is running on https://localhost:${PORT}`);
    });
  })
  .catch((err) => {
    console.log(err.message);
  });

const storeRouter = require("./routes/store");
const orderRouter = require("./routes/order");

// Set up routes for handling requests to /api/store and /api/order endpoints
app.use("/api/store", storeRouter);
app.use("/api/order", orderRouter);
