const https = require("https"); // Import the HTTPS module
const fs = require("fs"); // Import the File System module
const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
require("dotenv").config();

// Creating an Express.js app
const app = express();

// Using middleware to parse incoming requests
app.use(express.json({ limit: "100mb" }));
app.use(express.urlencoded({ limit: "100mb", extended: true }));
app.use(cors());

// Defining the server port and the MongoDB database URI using environment variables
const PORT = process.env.PORT || 443; // Default to HTTPS port 443
const URI = process.env.URI;

// Reading SSL certificate and private key generated by mkcert
const options = {
  key: fs.readFileSync("../certificate/localhost-key.pem"), // Path to the private key file
  cert: fs.readFileSync("../certificate/localhost.pem"), // Path to the certificate file
};

// Connecting to the MongoDB database and starting the HTTPS server
mongoose
  .connect(URI, { useUnifiedTopology: true })
  .then(() => {
    console.log("Connection to MongoDB successful");

    // Creating HTTPS server with SSL certificate
    https.createServer(options, app).listen(PORT, () => {
      console.log(`Secure server is running on https://localhost:${PORT}`);
    });
  })
  .catch((err) => {
    console.log(err.message);
  });

// Importing route modules
const paymentRouter = require("./routes/payment");
// Adding a route for handling payment-related requests
app.use("/api/payment", paymentRouter);
